### PR TITLE
Please reach out - important - regarding the code in this repository

### PR DESCRIPTION
**Pull request by r-andrew-dev**

### CODE REVIEW

**Comment by r-andrew-dev** [comment]
Hello! I am Rachael Andrew, open source program manager at Verizon Media (preivously Yahoo, AOL, Tech Crunch, Engadget, Millenial Media, Etc)We are concerned about the content in this repository. It may have been you meant to submit this code internally, but now we need this code taken down. [ At least the internal database mentioning part ] We are attempting to reach out here before going to a takedown notice with Github. Please reach out to me. GitHub ID r-andrew-dev, can verify my identity there. Email: hacktogether@verizonmedia.com [Alias to protect company email] Thank you! Please do contact us.

**Comment by kaustavbasu** [comment]
@r-andrew-dev i am happy to take down the objectionable code

**Comment by r-andrew-dev** [comment]
Excellent! Can we get confirmation on what Jarvis is? Was this internal
code accidentally pushed to public GitHub?

Thank you for working with us on this.

**Comment by r-andrew-dev** [comment]
Basically, if it was internal code accidentally pushed, no worries here.
Please just delete this repository.

**Comment by hyuan-dev** [comment]
Hi, I am Howard Yuan, an intellectual property attorney at Verizon Media, and work with Rachel and her open source program team.  I am following up on her request to remove the content from this repository and your acknowledgment to do so.  Could you please delete the repository at your earliest convenience and provide us a confirmation once you have done so at howard.yuan@verizonmedia.com, no further questions asked.  Much appreciated and thank you for your time!

**Pull request merged**
